name: Build and deploy Node.js app to Azure Web App - RepoScrapQL
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: npm install, build
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          REACT_APP_AUTH_URL: ${{secrets.AUTH_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          SECRET_USERNAME: ${{secrets.SECRET_USERNAME}}
          SECRET_PASSWORD: ${{secrets.SECRET_PASSWORD}}
          REACT_APP_API_TOKEN: ${{secrets.TOKEN_API}}
          REACT_APP_GRAPHQL_SERVER: ${{secrets.GRAPHQL_API}}
        run: |
          touch .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "REACT_APP_AUTH_URL=$REACT_APP_AUTH_URL" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "SECRET_USERNAME=$SECRET_USERNAME" >> .env
          echo "SECRET_PASSWORD=$SECRET_PASSWORD" >> .env
          echo "REACT_APP_API_TOKEN=$REACT_APP_API_TOKEN" >> .env
          echo "REACT_APP_GRAPHQL_SERVER=$REACT_APP_GRAPHQL_SERVER" >> .env
          npm install
          npm run build:api
          npm run test
          rm -rf src
       
      - name: Zip artifact for deployment
        run: |
          ls -la
          zip release.zip ./* -r
          ls -la
          

